# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bloguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='test',
        ),
    ]
