# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='last_mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
