# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170927_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(blank=True, help_text='不指定发布时间则视为草稿，可以指定未来时间，到时将自动发布。', null=True, verbose_name='发布时间'),
        ),
    ]
